### ISSUE TITLE
authentication error

### ISSUE THREAD

**Issue by sharryshah12** [plivo/plivo-android-sdk2-examples#1]
its working properly butt from last day it failes to login check the logcat

///////////////////////logcat///////////////////////
sip_auth_clien ...Authorization failed for snsone170720062259@phone.plivo.com: server rejected with stale=false
I/System.out: [backend-logs][onDebugMessage]16:11:21.474 pjsua_acc.c ....SIP registration error: Credential failed to authenticate (PJSIP_EFAILEDCREDENTIAL) [status=171100]
I/System.out: [backend-logs]onLoginFailed
D/PlivoInbound: Login failed
D/PlivoInbound: Login failed.....................................
I/System.out: [backend-logs][onDebugMessage]16:11:21.479 tsx0x7f5dfc98a Timeout timer event
I/System.out: [backend-logs][onDebugMessage]16:11:21.483 tsx0x7f5dfc98a .State changed from Completed to Terminated, event=TIMER
I/System.out: [backend-logs][onDebugMessage]16:11:21.491 tsx0x7f5dfc98a Timeout timer event
              [backend-logs][onDebugMessage]16:11:21.492 tsx0x7f5dfc98a .State changed from Terminated to Destroyed, event=TIMER
I/System.out: [backend-logs][onDebugMessage]16:11:21.493 tdta0x7f5df570 ..Destroying txdata Request msg REGISTER/cseq=36648 (tdta0x7f5df57000)
I/System.out: [backend-logs][onDebugMessage]16:11:21.494 tsx0x7f5dfc98a Transaction destroyed!

/////////////////////////////////////logcat//////////////////////////////////////
any solution please

**Comment by yuyongmao** [comment]
how i can make calling  to a phoneNumber just like 1622222222
I see the partial code blow in Outgoing Class

 public boolean call(String dest) {
        if (dest.length() > 0) {
            String sipUri = "sip:" + dest + "@phone.plivo.com";
            this.toContact = sipUri;
            this.active = true;
            if (plivo.Call(sipUri) != 0) {
                System.out.println("Call attempt failed. Check you destination address");
                this.active = false;
                return false;
            } else {
                return true;
            }
        } else {
            return false;
        }
    }

Dose this means that the "dest" will be regarded as a sip endpoint?

**Comment by eniyavan-muruganantham-plivo** [comment]
@sharryshah12  @yuyongmao 

Please raise the issue with support@plivo.com
