### ISSUE TITLE
I can't create a Plivo account

### ISSUE THREAD

**Issue by wall3001** [plivo/plivo-android-sdk2-examples#30]
This email is not allowed. Please input a valid work email.
I had try it by outlook、 gmail 、163、 hotmail 、icloud and so on.These all give me  some tips above.
Can you help me?

**Comment by eniyavan-muruganantham-plivo** [comment]
@wall3001 Please raise a ticket in https://support.plivo.com/support/tickets/new  or send mail to support@plivo.com

**Comment by kevinclarkadstech** [comment]
Yeah this is a stupid requirement!

**Comment by eniyavan-muruganantham-plivo** [comment]
@kevinclarkadstech

For security reasons, account creation with the public domain had been stopped.
https://support.plivo.com/hc/en-us/articles/360041203772-How-do-I-create-an-account-
Please look into this.
send mail to support@plivo.com for more information

**Comment by kevinclarkadstech** [comment]
@eniyavanm that is the dumbest reasoning. It would be better to improve your screening of accounts rather than banning personal emails. I will stick with Twilio who actually WANT my money.

**Comment by svierling** [comment]
@kevinclarkadstech same here. I had a project I was intending to pay plivo for, but they won't allow me to create an account with my personal gmail. Guess I'm moving to Twilio.

**Comment by Poli-cris** [comment]
> @kevinclarkadstech
> 
> For security reasons, account creation with the public domain had been stopped. https://support.plivo.com/hc/en-us/articles/360041203772-How-do-I-create-an-account- Please look into this. send mail to [support@plivo.com](mailto:support@plivo.com) for more information

even a professional email... Plivo wont allow me to open it

**Comment by Priya-gawhane** [comment]
Even I tried to access with my professional email but plivo is not allowing it.

**Comment by AdelBeit** [comment]
same issue here. guess you're ok with losing to your competition

**Comment by Kryptide** [comment]
Same issue here.
Fully willing and ready to spend money here yet I can't even use my business domain email.
It makes zero sense. I get "freemail" domains to an extent but blocking my personal business domain is wild.

**Comment by whatzbot-whatsapp-api** [comment]
Tried creating one with my work email but still getting the same error "This email domain isn't allowed at this time. Please try again with a different domain."

**Comment by chandailrc** [comment]
Same here. They are entering into the scam territory, I think. I have been having a back and forth with their sales guy and instead of the free tier he has been pushing hard for the $1000/month Enterprise plan repeatedly.
How can I commit to any paid plan if I don't even know whether your product works or will integrate well with my software? I need the sandbox tier to test things out. What is wrong with Plivo?
Got started with Twilio in seconds... and here I am stuck with Plivo for over a week.

**Comment by nilankar19** [comment]
I'm still facing the same issue. I tried using three different work email addresses, but I keep getting the message: "This email domain isn't allowed at this time" . I also checked the domain history and couldn't find anything unusual or any indication of why the domain might be blocked.

**Comment by jlurena** [comment]
lol glad I’m not the only one having problems. I emailed support and was told they can’t help. Guess I’m sticking with Twilio . Can’t even use my LLC professional email

**Comment by salian** [comment]
Very peculiar. Used a work .in domain, couldnt sign up. Based on the error message used a .com domain, still couldn't sign up. Not sure what they want.

**Comment by gulshan-4** [comment]
I tried my personal work email, tried everything., nothing worked.
**Can they at least give an example of a 'work email' and what they actually want?**
**What is considered "work email" if not my personal/custom email?**
