### ISSUE TITLE
NoSuchMethodError: com.plivo.endpoint.backend.plivoJNI in swig_module_init

### ISSUE THREAD

**Issue by abhinavsingh** [plivo/plivo-android-sdk2-examples#49]
We are getting the following in `release` build only and app crashes immediately on startup (since we have endpoint login around startup code)

```
NoSuchMethodError
no static method "Lcom/plivo/endpoint/backend/plivoJNI;.SwigDirector_PlivoAppCallback_onStarted(Lcom/plivo/endpoint/backend/PlivoAppCallback;Ljava/lang/String;)V"
```

I was suspecting missing proguard definitions but I didn't find any in the example Android project either.

Wondering whats going wrong and how to fix it.

NOTE: This works fine in `debug` and `profile` mode

**Comment by abhinavsingh** [comment]
jFYI, I am using `implementation 'com.plivo.endpoint:endpoint:2.0.19`

with `implementation 'com.plivo.endpoint:endpoint:3.0.1-beta.2'` I get the following during build time

```
error: cannot find symbol
            outgoing.callH(call.getString("phoneNumber"), headers);
                    ^
  symbol:   method callH(String,HashMap<String,String>)
  location: variable outgoing of type Outgoing
```

**Comment by abhinavsingh** [comment]
If I just use `outgoing.call` with `3.0.1-beta.2`, I then start getting

```
error: no suitable method found for newInstance(boolean,EventListener)
            endpoint = Endpoint.newInstance(false, kPlivoCallListener);
                               ^
    method Endpoint.newInstance(Context,boolean,EventListener) is not applicable
      (actual and formal argument lists differ in length)
    method Endpoint.newInstance(Context,boolean,EventListener,HashMap) is not applicable
      (actual and formal argument lists differ in length)
```

during build time

**Comment by shivmanish** [comment]
is any update on above issue? i also facing above

**Comment by Shashwatjxl** [comment]
is there any update, not able to release the app because of this issue

**Comment by markandrewjaxl** [comment]
Facing the same issue
